// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrjr3QoOlMaDUW0NhLzzzyNT1TsPKQKtw',
    appId: '1:481557455365:web:d73f33ae9e41b0ffc6b26c',
    messagingSenderId: '481557455365',
    projectId: 'power-tracker-6d39f',
    authDomain: 'power-tracker-6d39f.firebaseapp.com',
    storageBucket: 'power-tracker-6d39f.appspot.com',
    measurementId: 'G-236ZEP5T2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCLxyqC8Ecz4K9FkUn6tfzq4qOO5yuHiY',
    appId: '1:481557455365:android:b6d4b490b02b9be8c6b26c',
    messagingSenderId: '481557455365',
    projectId: 'power-tracker-6d39f',
    storageBucket: 'power-tracker-6d39f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPIaaXKVLxVv8_-8aaSwoFagp25ibeUFY',
    appId: '1:481557455365:ios:eae3f6c9f64d5e18c6b26c',
    messagingSenderId: '481557455365',
    projectId: 'power-tracker-6d39f',
    storageBucket: 'power-tracker-6d39f.appspot.com',
    iosClientId: '481557455365-u136a8csi8h8v2m8bhsq5fb844k9sjde.apps.googleusercontent.com',
    iosBundleId: 'com.example.powerTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrjr3QoOlMaDUW0NhLzzzyNT1TsPKQKtw',
    appId: '1:481557455365:web:abf4266a5794fbdec6b26c',
    messagingSenderId: '481557455365',
    projectId: 'power-tracker-6d39f',
    authDomain: 'power-tracker-6d39f.firebaseapp.com',
    storageBucket: 'power-tracker-6d39f.appspot.com',
    measurementId: 'G-0DKTVPMGPL',
  );
}
